### ISSUE TITLE
different string for value and label

### ISSUE THREAD

**Issue by nathangross** [bernhardh/nova-icon-select#2]
Firstly, I'm digging this package. It's working for me pretty well. I've got an issue though where I need a different string for the database vs the string for showing the icon in the Nova UI. I'm curious if that might be possible—perhaps through a custom config or something. 

So, I'm using the [blade icons package](https://github.com/blade-ui-kit/blade-icons) along with the [font awesome implementation of that] (https://github.com/owenvoke/blade-fontawesome). So in my front-end I'll call up an icon using the following syntax `<x-fas-edit  />` or dynamically like `<x-dynamic-component :component="$icon" />`

For the font-awesome icons to show up in Nova, I need to have the full label `fas fa-edit`. 

Would there be a way I might configure this package so that I could have separate strings for the front end and backend? I thought that might be what the `search` key was for but that doesn't seem to work. 

Perhaps something like this:

`
'label' => 'Edit',
'value' => 'fas-edit',
'display' => 'fas fa-edit`,
`

I dunno... any ideas?

**Comment by bernhardh** [comment]
Actually this should be doable, since the package already distingues between what you call `value` and `display` (in this package it is called `icon`).

```php
'500px' => [
    'label' => '500px',
    'value' => 'this-is-the-db-stored-value',
    'icon' => 'fab fa-500px'
],
```

Just have a look at the `IconProvider` class:

```php
/**
* @param array $options
*
* @return $this
*/
public function setOptions($options): self {
    $this->options = [];
    
    foreach($options AS $key => $option) {
        if(is_string($option)) {
            $this->addOption(
                $option,
                $key
            );
        }
        else {
            $this->addOption(
                $option["label"],
                isset($option["value"]) ? $option["value"] : $key,
                isset($option["icon"]) ? $option["icon"] : $option["value"],
                isset($option["search"]) ? $option["search"] : []
            );
        }
    }
    
    return $this;
}

/**
* @param string      $label
* @param string      $value
* @param string|null $icon
* @param array       $search
*
* @return IconProvider
*/
public function addOption(string $label, string $value, ?string $icon, array $search = []): self {
    if(!$icon) $icon = $value;
    
    $new = [
        "label" => $label,
        "value" => $value,
        "icon" => $icon,
    ];
    
    if($search) {
        $new["search"] = $search;
    }
    
    $this->options[] = $new;

    return $this;
}
```

**Comment by bernhardh** [comment]
Closing, because no respond.

**Comment by nathangross** [comment]
Hey—totally forgot to respond! Yes, this worked perfectly. Thanks for the nice package!
