### ISSUE TITLE
Using another icons set that require ohter html marckup

### ISSUE THREAD

**Issue by scramatte** [bernhardh/nova-icon-select#3]
Hello,

I need to use framework7 icons
https://framework7.io/icons/

What occurs is that I need another  html markup  like thi
<i class="f7-icons ...">house</i>

I've create my own icon Provider class but I don't know how can I change markup.
Ideally a method displayUsing  in the provider ...

Can you giive an hand ?
Regards

**Comment by bernhardh** [comment]
The `NovaIconSelect` extends the regular nova `Select` field. You could extend `NovaIconSelect` yourself and implement your own `displayUsing` method.

**Comment by scramatte** [comment]
Have you got some working examples ? I've seen some commented code in your source...

**Comment by bernhardh** [comment]
I have rechecked it.

> What occurs is that I need another html markup like thi

Sorry, you can only work with CSS classes and can't change the html markup at the moment.

What you would need is something like `<i class="f7-icons">arrowtriangle_up_square</i>` and thats not possible with this library right now. You could fork it and change the `resources/js/components/ShowOptions.vue` to somehing like this:

```vue
<template>
  <div>
    <span v-if="item.icon" class="w-6 mr-2">
      <i class="f7-icons">{{ item.icon }}</i>
    </span>
    <span v-html="item.label"></span>
  </div>
</template>
...
```
